# Variable 'CI' was defined in the Variables tab
# Variable 'IMAGE_INLINE_SIZE_LIMIT' was defined in the Variables tab
# Variable 'INLINE_RUNTIME_CHUNK' was defined in the Variables tab
trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Phase_1
  displayName: CI
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - task: YarnInstaller@3
    displayName: Install Yarn
  - task: Yarn@3
    displayName: yarn install
    inputs:
      arguments: install
  - task: Yarn@3
    displayName: yarn test
    inputs:
      arguments: test
  - task: Yarn@3
    displayName: yarn build
    inputs:
      arguments: build
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: build
...
