# Variable 'CI' was defined in the Variables tab
# Variable 'IMAGE_INLINE_SIZE_LIMIT' was defined in the Variables tab
# Variable 'INLINE_RUNTIME_CHUNK' was defined in the Variables tab
trigger:
  branches:
    include:
      - main
resources:
  repositories:
    - repository: self
      type: git
      ref: master
jobs:
  - job: Phase_1
    displayName: CI
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
  - task: Npm@1
        inputs:
      command: 'install'
  - task: Npm@1
        inputs:
      command: 'custom'
      customCommand: 'test'
  - task: Npm@1
        inputs:
      command: 'custom'
      customCommand: 'build'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          PathtoPublish: build
